### ISSUE TITLE
Cannot get example tests or own tests to run

### ISSUE THREAD

**Issue by CreeperShift** [ui5-community/wdi5#383]
**Describe the bug**
I've tried out WDI5 a few months ago and written a few very basics tests for UI5 and it worked fine. Now I wanted to revisit it for a new project and I can not get my very basic tests or the JS example tests in this repo to work. Chrome opens only for a split second then closes with the error in the output below.

**To Reproduce**

Checked out this repo, npm install
npm run _startApp:js 
then 
npm run test:webserver -w examples/ui5-js-app

**Expected behavior**
The tests to run

**Logs/Console Output**

Output from tests
https://pastebin.com/Mycg2ZCF

**Runtime Env (please complete the following information):**

- `wdi5/wdio-ui5-service`-version: [e.g. 0.8.1]
- `UI5` version: [1.109.0]
- `wdio`-version (output of `wdio --version`): 7.26.0
- `node`-version (output of `node --version`): v16.18.1
- `npm`-version: 9.1.3
- OS: Windows 11
- Browser + Version: Chrome 108.0.5359.95

**Additional context**
I'm unsure if this is some kind of issue with my chrome install/version but I'm unsure how to debug this.

**Comment by CreeperShift** [comment]
Thank you both, adjusting the chromedriver version to 108 did indeed fix the issue I was having and the example tests are now running without issues.

I also did the same for the project following the installation guide here: https://ui5-community.github.io/wdi5/#/installation (fresh UI5 project generated with Yo easyui5) using npm init wdi5@latest,  however even a simple test with just a console log throws the following error:

> ERROR @wdio/utils:initialiseServices: Error: Couldn't initialise "wdio-ui5-service".
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './build/multiremote' is not defined by "exports" in C:\Playground\E2ETesting\test-install2\node_modules\webdriverio\package.json
    at new NodeError (node:internal/errors:387:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:365:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:649:3)
    at resolveExports (node:internal/modules/cjs/loader:522:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:562:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:971:27)
    at Function.Module._load (node:internal/modules/cjs/loader:833:27)
    at Module.require (node:internal/modules/cjs/loader:1057:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (C:\Playground\E2ETesting\test-install2\node_modules\wdio-ui5-service\dist\service.js:50:21)
    at safeRequire (C:\Playground\E2ETesting\test-install2\node_modules\@wdio\utils\build\utils.js:192:15)
    at initialisePlugin (C:\Playground\E2ETesting\test-install2\node_modules\@wdio\utils\build\initialisePlugin.js:37:44)
    at initialiseServices (C:\Playground\E2ETesting\test-install2\node_modules\@wdio\utils\build\initialiseServices.js:59:56)
    at initialiseLauncherService (C:\Playground\E2ETesting\test-install2\node_modules\@wdio\utils\build\initialiseServices.js:86:26)
    at Launcher.run (C:\Playground\E2ETesting\test-install2\node_modules\@wdio\cli\build\launcher.js:73:103)
    at launch (C:\Playground\E2ETesting\test-install2\node_modules\@wdio\cli\build\commands\run.js:126:21)
    at Object.handler (C:\Playground\E2ETesting\test-install2\node_modules\@wdio\cli\build\commands\run.js:165:16)
    at C:\Playground\E2ETesting\test-install2\node_modules\yargs\build\index.cjs:1:8891
    at j (C:\Playground\E2ETesting\test-install2\node_modules\yargs\build\index.cjs:1:4956)
    at M.handleValidationAndGetResult (C:\Playground\E2ETesting\test-install2\node_modules\yargs\build\index.cjs:1:8860)

Dependencies as installed by the wdi5 init:

> "devDependencies": {
    "@sapui5/ts-types-esm": "1.109.0",
    "@ui5/cli": "latest",
    "@wdio/cli": "^7",
    "@wdio/local-runner": "^7",
    "@wdio/mocha-framework": "^7",
    "@wdio/spec-reporter": "^7",
    "chromedriver": "^108",
    "eslint": "^8.27.0",
    "ui5-middleware-livereload": "^0.7.0",
    "wdio-chromedriver-service": "latest",
    "wdio-ui5-service": "latest"
  },

**Comment by Siolto** [comment]
That's because wdi5 currently [does not support WebdriverIO V8](https://twitter.com/_wdi5_/status/1599730463064887297). The `npm init wdi5` installs a wrong version of the `wdio-chromedriver-service`. Try it with `^7.3.2` and it should work.

We are already working on a solution that `npm init wdi5` works again ootb.

**Comment by CreeperShift** [comment]
> That's because wdi5 currently [does not support WebdriverIO V8](https://twitter.com/_wdi5_/status/1599730463064887297). The `npm init wdi5` installs a wrong version of the `wdio-chromedriver-service`. Try it with `^7.3.2` and it should work.
> 
> We are already working on a solution that `npm init wdi5` works again ootb.

Thank you for the quick help that did indeed fix it! Seems like it was just unlucky timing to follow the documentation right now.
