### ISSUE TITLE
Couldn't initialise "wdio-ui5-service".

### ISSUE THREAD

**Issue by robbymanis** [ui5-community/wdi5#408]
**Describe the bug**
Couldn't initialise "wdio-ui5-service". If I remove `ui5` from my list of services `services: ['chromedriver','vscode','ui5'],` the test runs fine.
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './build/multiremote' is not defined by "exports" in C:\SAPDevelop\openui5-basic-template-app\node_modules\webdriverio\package.json

**To Reproduce**

Follow: https://ui5-community.github.io/wdi5/#/installation?id=b-guided-install-via-wdio-cli
run `wdio run wdio.conf.js`

**Expected behavior**
The sample `example.e2e.js` should run:
```js
describe('My Login application', () => {
    it('should login with valid credentials', async () => {
        await browser.url(`https://the-internet.herokuapp.com/login`)

        await $('#username').setValue('tomsmith')
        await $('#password').setValue('SuperSecretPassword!')
        await $('button[type="submit"]').click()

        await expect($('#flash')).toBeExisting()
        await expect($('#flash')).toHaveTextContaining(
            'You logged into a secure area!')
    })
})
```

**Logs/Console Output**
if applicable, please copypasta _code-fenced_ log output, e.g.

```shell
PS C:\SAPDevelop\openui5-basic-template-app> npm run wdio

> openui5-basic-template-app@0.1.0 wdio
> wdio run wdio.conf.js


Execution of 1 workers started at 2023-01-23T19:24:44.470Z

2023-01-23T19:24:46.404Z INFO @wdio/local-runner: Shutting down spawned worker
2023-01-23T19:24:46.656Z INFO @wdio/local-runner: Waiting for 0 to shut down gracefully
2023-01-23T19:24:46.656Z INFO @wdio/local-runner: shutting down
Error in "undefined"
Error: Failed to initilialise launcher service unknown: Error: Couldn't initialise "wdio-ui5-service".
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './build/multiremote' is not defined by "exports" in C:\SAPDevelop\openui5-basic-template-app\node_modules\webdriverio\package.json
    at new NodeError (node:internal/errors:400:5)
    at exportsNotFound (node:internal/modules/esm/resolve:361:10)
    at packageExportsResolve (node:internal/modules/esm/resolve:697:9)
    at resolveExports (node:internal/modules/cjs/loader:538:36)
    at Module._findPath (node:internal/modules/cjs/loader:607:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1025:27)
    at Module._load (node:internal/modules/cjs/loader:885:27)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (C:\SAPDevelop\openui5-basic-template-app\node_modules\wdio-ui5-service\dist\service.js:50:21)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Module._load (node:internal/modules/cjs/loader:922:12)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at safeImport (file:///C:/SAPDevelop/openui5-basic-template-app/node_modules/@wdio/utils/build/utils.js:210:15)
    at async initialisePlugin (file:///C:/SAPDevelop/openui5-basic-template-app/node_modules/@wdio/utils/build/initialisePlugin.js:32:20)
    at async initialiseServices (file:///C:/SAPDevelop/openui5-basic-template-app/node_modules/@wdio/utils/build/initialiseServices.js:53:25)
    at async initialiseLauncherService (file:///C:/SAPDevelop/openui5-basic-template-app/node_modules/@wdio/utils/build/initialiseServices.js:81:26)
    at async Launcher.run (file:///C:/SAPDevelop/openui5-basic-template-app/node_modules/@wdio/cli/build/launcher.js:69:65)
    at initialiseLauncherService (file:///C:/SAPDevelop/openui5-basic-template-app/node_modules/@wdio/utils/build/initialiseServices.js:118:15)
    at async Launcher.run (file:///C:/SAPDevelop/openui5-basic-template-app/node_modules/@wdio/cli/build/launcher.js:69:65)
Error: Failed to initilialise launcher service unknown: Error: Couldn't initialise "wdio-ui5-service".
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './build/multiremote' is not defined by "exports" in C:\SAPDevelop\openui5-basic-template-app\node_modules\webdriverio\package.json
    at new NodeError (node:internal/errors:400:5)
    at exportsNotFound (node:internal/modules/esm/resolve:361:10)
    at packageExportsResolve (node:internal/modules/esm/resolve:697:9)
    at resolveExports (node:internal/modules/cjs/loader:538:36)
    at Module._findPath (node:internal/modules/cjs/loader:607:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1025:27)
    at Module._load (node:internal/modules/cjs/loader:885:27)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (C:\SAPDevelop\openui5-basic-template-app\node_modules\wdio-ui5-service\dist\service.js:50:21)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Module._load (node:internal/modules/cjs/loader:922:12)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at safeImport (file:///C:/SAPDevelop/openui5-basic-template-app/node_modules/@wdio/utils/build/utils.js:210:15)
    at async initialisePlugin (file:///C:/SAPDevelop/openui5-basic-template-app/node_modules/@wdio/utils/build/initialisePlugin.js:32:20)
    at async initialiseServices (file:///C:/SAPDevelop/openui5-basic-template-app/node_modules/@wdio/utils/build/initialiseServices.js:53:25)
    at async initialiseLauncherService (file:///C:/SAPDevelop/openui5-basic-template-app/node_modules/@wdio/utils/build/initialiseServices.js:81:26)
    at async Launcher.run (file:///C:/SAPDevelop/openui5-basic-template-app/node_modules/@wdio/cli/build/launcher.js:69:65)
    at initialiseLauncherService (file:///C:/SAPDevelop/openui5-basic-template-app/node_modules/@wdio/utils/build/initialiseServices.js:118:15)
    at async Launcher.run (file:///C:/SAPDevelop/openui5-basic-template-app/node_modules/@wdio/cli/build/launcher.js:69:65)
PS C:\SAPDevelop\openui5-basic-template-app> 
```

**Screenshots**
if applicable, add screenshots to help explain your problem.

**Runtime Env (please complete the following information):**

- `wdi5/wdio-ui5-service`-version: 1.0.5
- `UI5` version: [e.g. 1.98.0] Not applicable to this issue, but 1.96 
- `wdio`-version (output of `wdio --version`): see package.json
- `node`-version (output of `node --version`): 18.13.0
- OS: Windows 11
- Browser + Version Google Chrome 109.0.5414.75 (Official Build) (64-bit) 

**Additional context**
My `package.json`
```json
{
    "name": "openui5-basic-template-app",
    "version": "0.1.0",
    "description": "Best-practice starting point for building a freestyle app",
    "private": true,
    "scripts": {
        "start": "ui5 serve -o /index.html",
        "lint": "eslint webapp",
        "karma": "karma start",
        "karma-ci": "karma start karma-ci.conf.js",
        "watch": "npm run karma",
        "test": "npm run lint && rimraf coverage && npm run karma-ci",
        "build": "rimraf dist && ui5 build --a",
        "wdio": "wdio run wdio.conf.js"
    },
    "devDependencies": {
        "@ui5/cli": "^2.14.2",
        "@wdio/cli": "^8.2.1",
        "@wdio/local-runner": "^8.2.1",
        "@wdio/mocha-framework": "^8.2.1",
        "@wdio/spec-reporter": "^8.1.2",
        "chromedriver": "^109.0.0",
        "eslint": "^8.6.0",
        "karma": "^6.3.10",
        "karma-chrome-launcher": "^3.1.0",
        "karma-coverage": "^2.1.0",
        "karma-ui5": "^2.4.0",
        "rimraf": "^3.0.2",
        "ui5-middleware-livereload": "^0.7.0",
        "wdio-chromedriver-service": "^8.0.1",
        "wdio-ui5-service": "^1.0.5",
        "wdio-vscode-service": "^5.0.0"
    },
    "ui5": {
        "dependencies": [
            "ui5-middleware-livereload"
        ]
    }
}
```

```javascript
exports.config = {
    //
    // ====================
    // Runner Configuration
    // ====================
    // WebdriverIO supports running e2e tests as well as unit and component tests.
    runner: 'local',
    
    //
    // ==================
    // Specify Test Files
    // ==================
    // Define which test specs should run. The pattern is relative to the directory
    // of the configuration file being run.
    //
    // The specs are defined as an array of spec files (optionally using wildcards
    // that will be expanded). The test for each spec file will be run in a separate
    // worker process. In order to have a group of spec files run in the same worker
    // process simply enclose them in an array within the specs array.
    //
    // If you are calling `wdio` from an NPM script (see https://docs.npmjs.com/cli/run-script),
    // then the current working directory is where your `package.json` resides, so `wdio`
    // will be called from there.
    //
    specs: [
        './test/specs/**/*.js'
    ],
    // Patterns to exclude.
    exclude: [
        // 'path/to/excluded/files'
    ],
    //
    // ============
    // Capabilities
    // ============
    // Define your capabilities here. WebdriverIO can run multiple capabilities at the same
    // time. Depending on the number of capabilities, WebdriverIO launches several test
    // sessions. Within your capabilities you can overwrite the spec and exclude options in
    // order to group specific specs to a specific capability.
    //
    // First, you can define how many instances should be started at the same time. Let's
    // say you have 3 different capabilities (Chrome, Firefox, and Safari) and you have
    // set maxInstances to 1; wdio will spawn 3 processes. Therefore, if you have 10 spec
    // files and you set maxInstances to 10, all spec files will get tested at the same time
    // and 30 processes will get spawned. The property handles how many capabilities
    // from the same test should run tests.
    //
    maxInstances: 10,
    //
    // If you have trouble getting all important capabilities together, check out the
    // Sauce Labs platform configurator - a great tool to configure your capabilities:
    // https://saucelabs.com/platform/platform-configurator
    //
    capabilities: [{
    
        // maxInstances can get overwritten per capability. So if you have an in-house Selenium
        // grid with only 5 firefox instances available you can make sure that not more than
        // 5 instances get started at a time.
        maxInstances: 5,
        //
        browserName: 'chrome',
        acceptInsecureCerts: true
        // If outputDir is provided WebdriverIO can capture driver session logs
        // it is possible to configure which logTypes to include/exclude.
        // excludeDriverLogs: ['*'], // pass '*' to exclude all driver session logs
        // excludeDriverLogs: ['bugreport', 'server'],
    }],
    //
    // ===================
    // Test Configurations
    // ===================
    // Define all options that are relevant for the WebdriverIO instance here
    //
    // Level of logging verbosity: trace | debug | info | warn | error | silent
    logLevel: 'info',
    //
    // Set specific log levels per logger
    // loggers:
    // - webdriver, webdriverio
    // - @wdio/browserstack-service, @wdio/devtools-service, @wdio/sauce-service
    // - @wdio/mocha-framework, @wdio/jasmine-framework
    // - @wdio/local-runner
    // - @wdio/sumologic-reporter
    // - @wdio/cli, @wdio/config, @wdio/utils
    // Level of logging verbosity: trace | debug | info | warn | error | silent
    // logLevels: {
    //     webdriver: 'info',
    //     '@wdio/appium-service': 'info'
    // },
    //
    // If you only want to run your tests until a specific amount of tests have failed use
    // bail (default is 0 - don't bail, run all tests).
    bail: 0,
    //
    // Set a base URL in order to shorten url command calls. If your `url` parameter starts
    // with `/`, the base url gets prepended, not including the path portion of your baseUrl.
    // If your `url` parameter starts without a scheme or `/` (like `some/path`), the base url
    // gets prepended directly.
    baseUrl: 'http://localhost:8080',
    //
    // Default timeout for all waitFor* commands.
    waitforTimeout: 10000,
    //
    // Default timeout in milliseconds for request
    // if browser driver or grid doesn't send response
    connectionRetryTimeout: 120000,
    //
    // Default request retries count
    connectionRetryCount: 3,
    //
    // Test runner services
    // Services take over a specific job you don't want to take care of. They enhance
    // your test setup with almost no effort. Unlike plugins, they don't add new
    // commands. Instead, they hook themselves up into the test process.
    services: ['chromedriver','vscode','ui5'],
    
    // Framework you want to run your specs with.
    // The following are supported: Mocha, Jasmine, and Cucumber
    // see also: https://webdriver.io/docs/frameworks
    //
    // Make sure you have the wdio adapter package for the specific framework installed
    // before running any tests.
    framework: 'mocha',
    //
    // The number of times to retry the entire specfile when it fails as a whole
    // specFileRetries: 1,
    //
    // Delay in seconds between the spec file retry attempts
    // specFileRetriesDelay: 0,
    //
    // Whether or not retried specfiles should be retried immediately or deferred to the end of the queue
    // specFileRetriesDeferred: false,
    //
    // Test reporter for stdout.
    // The only one supported by default is 'dot'
    // see also: https://webdriver.io/docs/dot-reporter
    reporters: ['spec'],


    
    //
    // Options to be passed to Mocha.
    // See the full list at http://mochajs.org/
    mochaOpts: {
        ui: 'bdd',
        timeout: 60000
    },
    //
    // =====
    // Hooks
    // =====
    // WebdriverIO provides several hooks you can use to interfere with the test process in order to enhance
    // it and to build services around it. You can either apply a single function or an array of
    // methods to it. If one of them returns with a promise, WebdriverIO will wait until that promise got
    // resolved to continue.
    /**
     * Gets executed once before all workers get launched.
     * @param {Object} config wdio configuration object
     * @param {Array.<Object>} capabilities list of capabilities details
     */
    // onPrepare: function (config, capabilities) {
    // },
    /**
     * Gets executed before a worker process is spawned and can be used to initialise specific service
     * for that worker as well as modify runtime environments in an async fashion.
     * @param  {String} cid      capability id (e.g 0-0)
     * @param  {[type]} caps     object containing capabilities for session that will be spawn in the worker
     * @param  {[type]} specs    specs to be run in the worker process
     * @param  {[type]} args     object that will be merged with the main configuration once worker is initialized
     * @param  {[type]} execArgv list of string arguments passed to the worker process
     */
    // onWorkerStart: function (cid, caps, specs, args, execArgv) {
    // },
    /**
     * Gets executed just after a worker process has exited.
     * @param  {String} cid      capability id (e.g 0-0)
     * @param  {Number} exitCode 0 - success, 1 - fail
     * @param  {[type]} specs    specs to be run in the worker process
     * @param  {Number} retries  number of retries used
     */
    // onWorkerEnd: function (cid, exitCode, specs, retries) {
    // },
    /**
     * Gets executed just before initialising the webdriver session and test framework. It allows you
     * to manipulate configurations depending on the capability or spec.
     * @param {Object} config wdio configuration object
     * @param {Array.<Object>} capabilities list of capabilities details
     * @param {Array.<String>} specs List of spec file paths that are to be run
     * @param {String} cid worker id (e.g. 0-0)
     */
    // beforeSession: function (config, capabilities, specs, cid) {
    // },
    /**
     * Gets executed before test execution begins. At this point you can access to all global
     * variables like `browser`. It is the perfect place to define custom commands.
     * @param {Array.<Object>} capabilities list of capabilities details
     * @param {Array.<String>} specs        List of spec file paths that are to be run
     * @param {Object}         browser      instance of created browser/device session
     */
    // before: function (capabilities, specs) {
    // },
    /**
     * Runs before a WebdriverIO command gets executed.
     * @param {String} commandName hook command name
     * @param {Array} args arguments that command would receive
     */
    // beforeCommand: function (commandName, args) {
    // },
    /**
     * Hook that gets executed before the suite starts
     * @param {Object} suite suite details
     */
    // beforeSuite: function (suite) {
    // },
    /**
     * Function to be executed before a test (in Mocha/Jasmine) starts.
     */
    // beforeTest: function (test, context) {
    // },
    /**
     * Hook that gets executed _before_ a hook within the suite starts (e.g. runs before calling
     * beforeEach in Mocha)
     */
    // beforeHook: function (test, context) {
    // },
    /**
     * Hook that gets executed _after_ a hook within the suite starts (e.g. runs after calling
     * afterEach in Mocha)
     */
    // afterHook: function (test, context, { error, result, duration, passed, retries }) {
    // },
    /**
     * Function to be executed after a test (in Mocha/Jasmine only)
     * @param {Object}  test             test object
     * @param {Object}  context          scope object the test was executed with
     * @param {Error}   result.error     error object in case the test fails, otherwise `undefined`
     * @param {Any}     result.result    return object of test function
     * @param {Number}  result.duration  duration of test
     * @param {Boolean} result.passed    true if test has passed, otherwise false
     * @param {Object}  result.retries   informations to spec related retries, e.g. `{ attempts: 0, limit: 0 }`
     */
    // afterTest: function(test, context, { error, result, duration, passed, retries }) {
    // },


    /**
     * Hook that gets executed after the suite has ended
     * @param {Object} suite suite details
     */
    // afterSuite: function (suite) {
    // },
    /**
     * Runs after a WebdriverIO command gets executed
     * @param {String} commandName hook command name
     * @param {Array} args arguments that command would receive
     * @param {Number} result 0 - command success, 1 - command error
     * @param {Object} error error object if any
     */
    // afterCommand: function (commandName, args, result, error) {
    // },
    /**
     * Gets executed after all tests are done. You still have access to all global variables from
     * the test.
     * @param {Number} result 0 - test pass, 1 - test fail
     * @param {Array.<Object>} capabilities list of capabilities details
     * @param {Array.<String>} specs List of spec file paths that ran
     */
    // after: function (result, capabilities, specs) {
    // },
    /**
     * Gets executed right after terminating the webdriver session.
     * @param {Object} config wdio configuration object
     * @param {Array.<Object>} capabilities list of capabilities details
     * @param {Array.<String>} specs List of spec file paths that ran
     */
    // afterSession: function (config, capabilities, specs) {
    // },
    /**
     * Gets executed after all workers got shut down and the process is about to exit. An error
     * thrown in the onComplete hook will result in the test run failing.
     * @param {Object} exitCode 0 - success, 1 - fail
     * @param {Object} config wdio configuration object
     * @param {Array.<Object>} capabilities list of capabilities details
     * @param {<Object>} results object containing test results
     */
    // onComplete: function(exitCode, config, capabilities, results) {
    // },
    /**
    * Gets executed when a refresh happens.
    * @param {String} oldSessionId session ID of the old session
    * @param {String} newSessionId session ID of the new session
    */
    // onReload: function(oldSessionId, newSessionId) {
    // }
}

```

**Comment by vobu** [comment]
this happens b/c `wdi5` is not compatible with `wdio`^8 yet. 
please either downgrade all `wdio`-related packages to ^7 manually - or use `npm init wdi5` in the root of your ui5 app. the latter will take care of installing v7 dependencies only.

**Comment by robbymanis** [comment]
should this be called out somewhere here? https://ui5-community.github.io/wdi5/#/installation?id=b-guided-install-via-wdio-cli I don't think this is immediately obvious to new users

**Comment by vobu** [comment]
absolutely! would you mind sketching up a quick PR for the docs? (or even a first shot at wdio v8 support 😉 ?)
