### ISSUE TITLE
Error on using the method `getFormContainers` on `sap.ui.layout.form.Form`

### ISSUE THREAD

**Issue by marianfoo** [ui5-community/wdi5#488]
# **Describe the bug**
I try to get the Form Container of a Simple Form with `getFormContainers()`

## XML View
https://github.com/marianfoo/ui5-cc-excelUpload/blob/a2ec7c3910ee5456a6b927e4fd0cf4d444f32c12/packages/ui5-cc-excelUpload/src/fragment/OptionsDialog.fragment.xml#L13-L32

```XML
        <f:SimpleForm editable="true" layout="ResponsiveGridLayout" labelSpanXL="3" labelSpanL="3" labelSpanM="3" labelSpanS="12" adjustLabelSpan="false" class="centered">
            <f:content>
              <Label text="{i18n>optionsDialogStrict}" visible="{= ${availableOptions>/strict}}" />
              <CheckBox
                selected="{options>/strict}" visible="{= ${availableOptions>/strict}}" />
              <Label text="{i18n>optionsDialogFieldMatchType}" visible="{= ${availableOptions>/fieldMatchType}}"/>
              <Select
                selectedKey="{options>/fieldMatchType}" visible="{= ${availableOptions>/fieldMatchType}}">
                <core:Item key="labelTypeBrackets" text="{i18n>optionsDialogLabelTypeBrackets}" />
                <core:Item key="label" text="{i18n>optionsDialogLabel}" />
              </Select>
              <Label text="{i18n>optionsDialogDecimalSeperator}" visible="{= ${availableOptions>/decimalSeperator}}"/>
              <Select
                selectedKey="{options>/decimalSeparator}" visible="{= ${availableOptions>/decimalSeperator}}">
                <core:Item key="" text="{i18n>optionsDialogBrowserDefault}" />
                <core:Item key="," text="{i18n>optionsDialogComma} `,`" />
                <core:Item key="." text="{i18n>optionsDialogDot} `.`" />
              </Select>
            </f:content>
          </f:SimpleForm>
```

## Test
https://github.com/marianfoo/ui5-cc-excelUpload/blob/3194938d95f3d91fca15bb83cdc265be82c21127/examples/test/specs/all/SetAvailableOptionsListReport.test.js#L65-L77

```js
	it("Check only strict available", async () => {
		const form = await browser.asControl({
			selector: {
				interaction: "root",
				id: "__form0--Form"
			}
		});
                //  here is the error 'error retrieving control'
		const formContainers = await form.getFormContainers();	
		const formContainer = await formContainers[0]	
		const formElements = await formContainer.getVisibleFormElements();

		expect(formElements.length).toBe(1);
	});
```

## Error
![image](https://github.com/ui5-community/wdi5/assets/13335743/bf37166d-a931-4958-b3c3-2465950bc8bc)

# **To Reproduce**

1. Setup
```shell
git clone https://github.com/marianfoo/ui5-cc-excelUpload
git checkout feat/option-user
pnpm i
```
2. Start App
```shell
pnpm run start
```
3. Run Test
```shell
pnpm --filter ui5-cc-excelupload-sample  test -- ordersv4fe 108 --spec SetAvailableOptionsListReport.test
```

**Expected behavior**

**Logs/Console Output**

```shell
pnpm --filter ui5-cc-excelupload-sample  test -- ordersv4fe 108 --spec SetAvailableOptionsListReport.test

> ui5-cc-excelupload-sample@0.0.0 test /Users/marianzeis/DEV/ui5-cc-excelUpload/examples
> wdio run ./test/wdio-base.conf.js "ordersv4fe" "108" "--spec" "SetAvailableOptionsListReport.test"


Execution of 1 spec files started at 2023-06-20T11:11:17.742Z

[0-0] RUNNING in chrome - /test/specs/all/SetAvailableOptionsListReport.test.js
[0-0] [wdi5] call of _getControl() failed because of: Error: No DOM element found using the control selector {"id":"__form0--FC-NoHead"}
[wdi5] error retrieving control: __form0--FC-NoHead
[0-0] TypeError in "Upload File List Report Check only strict available"
TypeError: formContainer.getVisibleFormElements is not a function
    at Context.<anonymous> (/Users/marianzeis/DEV/ui5-cc-excelUpload/examples/test/specs/all/SetAvailableOptionsListReport.test.js:74:44)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Context.executeAsync (/Users/marianzeis/DEV/ui5-cc-excelUpload/node_modules/.pnpm/@wdio+utils@7.0.0/node_modules/@wdio/utils/build/shim.js:137:16)
    at async Context.exports.testFrameworkFnWrapper (/Users/marianzeis/DEV/ui5-cc-excelUpload/node_modules/.pnpm/@wdio+utils@7.0.0/node_modules/@wdio/utils/build/test-framework/testFnWrapper.js:51:18)
[0-0] FAILED in chrome - /test/specs/all/SetAvailableOptionsListReport.test.js

 "spec" Reporter:
------------------------------------------------------------------
[chrome 114.0.5735.133 mac os x #0-0] Spec: /Users/marianzeis/DEV/ui5-cc-excelUpload/examples/test/specs/all/SetAvailableOptionsListReport.test.js
[chrome 114.0.5735.133 mac os x #0-0] Running: chrome (v114.0.5735.133) on mac os x
[chrome 114.0.5735.133 mac os x #0-0] Session ID: 87848893341b82484d8b912a8b6a850a
[chrome 114.0.5735.133 mac os x #0-0]
[chrome 114.0.5735.133 mac os x #0-0] Upload File List Report
[chrome 114.0.5735.133 mac os x #0-0]    ✓ should trigger search on ListReport page
[chrome 114.0.5735.133 mac os x #0-0]    ✓ Open ExcelUpload Dialog
[chrome 114.0.5735.133 mac os x #0-0]    ✓ Open Options Menu
[chrome 114.0.5735.133 mac os x #0-0]    ✖ Check only strict available
[chrome 114.0.5735.133 mac os x #0-0]
[chrome 114.0.5735.133 mac os x #0-0] 3 passing (7.5s)
[chrome 114.0.5735.133 mac os x #0-0] 1 failing
[chrome 114.0.5735.133 mac os x #0-0]
[chrome 114.0.5735.133 mac os x #0-0] 1) Upload File List Report Check only strict available
[chrome 114.0.5735.133 mac os x #0-0] formContainer.getVisibleFormElements is not a function
[chrome 114.0.5735.133 mac os x #0-0] TypeError: formContainer.getVisibleFormElements is not a function
[chrome 114.0.5735.133 mac os x #0-0]     at Context.<anonymous> (/Users/marianzeis/DEV/ui5-cc-excelUpload/examples/test/specs/all/SetAvailableOptionsListReport.test.js:74:44)
[chrome 114.0.5735.133 mac os x #0-0]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[chrome 114.0.5735.133 mac os x #0-0]     at async Context.executeAsync (/Users/marianzeis/DEV/ui5-cc-excelUpload/node_modules/.pnpm/@wdio+utils@7.0.0/node_modules/@wdio/utils/build/shim.js:137:16)
[chrome 114.0.5735.133 mac os x #0-0]     at async Context.exports.testFrameworkFnWrapper (/Users/marianzeis/DEV/ui5-cc-excelUpload/node_modules/.pnpm/@wdio+utils@7.0.0/node_modules/@wdio/utils/build/test-framework/testFnWrapper.js:51:18)


Spec Files:      0 passed, 1 failed, 1 total (100% completed) in 00:00:10 
```

**Screenshots**
if applicable, add screenshots to help explain your problem.

**Runtime Env (please complete the following information):**

- `wdi5/wdio-ui5-service`-version: `1.5.0`
- `UI5` version: `1.108.14`
- `wdio`-version (output of `wdio --version`): v7
- `node`-version (output of `node --version`): 18.14.0
- OS:  macOS
- Browser + Version Chrome 1.114

# **Additional context**

Regarding the error `error retrieving control: __form0--FC-NoHead`, i can´t find this id in the html source either.  
Here is the source for the simple form.

<details>

```html
<div id="__form0" data-sap-ui="__form0" class="sapUiSimpleForm centered">
  <div
    id="__form0--Form"
    data-sap-ui="__form0--Form"
    data-sap-ui-customfastnavgroup="true"
    role="form"
    class="sapUiForm sapUiFormLblColon sapUiFormM sapUiFormEdit sapUiFormEdit-CTX"
  >
    <div
      id="__form0--Layout"
      data-sap-ui="__form0--Layout"
      class="sapUiFormResGrid sapUiFormBackgrTranslucent"
    >
      <div
        id="__form0--FC-NoHead--Grid"
        data-sap-ui="__form0--FC-NoHead--Grid"
        class="sapUiRespGrid sapUiRespGridHSpace0 sapUiRespGridVSpace0 sapUiFormResGridCont sapUiRespGridOverflowHidden sapUiRespGridMedia-Std-Phone"
      >
        <div
          id="__form0--FC-NoHead--Grid-wrapperfor-__label8"
          class="sapUiRespGridBreak sapUiRespGridSpanXL3 sapUiRespGridSpanL3 sapUiRespGridSpanM3 sapUiRespGridSpanS12 sapUiFormElementLbl"
        >
          <label
            id="__label8"
            data-sap-ui="__label8"
            for="__box1"
            class="sapMLabel sapUiSelectable sapMLabelWrapped sapMLabelMaxWidth sapUiFormLabel-CTX"
            style="text-align: left"
            ><span id="__label8-text" class="sapMLabelTextWrapper"
              ><bdi id="__label8-bdi">Strict Mode</bdi></span
            ><span
              data-colon=":"
              aria-hidden="true"
              class="sapMLabelColonAndRequired"
            ></span
          ></label>
        </div>
        <div
          id="__form0--FC-NoHead--Grid-wrapperfor-__box1"
          class="sapUiRespGridSpanXL9 sapUiRespGridSpanL9 sapUiRespGridSpanM9 sapUiRespGridSpanS12"
        >
          <div
            id="__box1"
            data-sap-ui="__box1"
            data-ui5-accesskey=""
            tabindex="0"
            aria-labelledby="__label8"
            role="checkbox"
            aria-checked="false"
            class="sapMCb"
          >
            <div id="__box1-CbBg" class="sapMCbBg sapMCbHoverable sapMCbMark">
              <input id="__box1-CB" type="CheckBox" />
            </div>
          </div>
        </div>
        <div
          id="__form0--FC-NoHead--Grid-wrapperfor-__label9"
          class="sapUiRespGridBreak sapUiRespGridSpanXL3 sapUiRespGridSpanL3 sapUiRespGridSpanM3 sapUiRespGridSpanS12 sapUiFormElementLbl"
        >
          <label
            id="__label9"
            data-sap-ui="__label9"
            for="__select0-hiddenSelect"
            class="sapMLabel sapUiSelectable sapMLabelWrapped sapMLabelMaxWidth sapUiFormLabel-CTX"
            style="text-align: left"
            ><span id="__label9-text" class="sapMLabelTextWrapper"
              ><bdi id="__label9-bdi">Field Match Type</bdi></span
            ><span
              data-colon=":"
              aria-hidden="true"
              class="sapMLabelColonAndRequired"
            ></span
          ></label>
        </div>
        <div
          id="__form0--FC-NoHead--Grid-wrapperfor-__select0"
          class="sapUiRespGridSpanXL9 sapUiRespGridSpanL9 sapUiRespGridSpanM9 sapUiRespGridSpanS12"
        >
          <div
            id="__select0"
            data-sap-ui="__select0"
            tabindex="-1"
            class="sapMSlt sapMSltDefault sapMSltMinWidth sapMSltHoverable sapMSltWithArrow"
            style="width: 100%; max-width: 100%"
          >
            <div
              id="__select0-hiddenSelect"
              role="combobox"
              aria-roledescription="Listbox"
              aria-readonly="false"
              aria-expanded="false"
              aria-labelledby="__label9"
              aria-haspopup="listbox"
              tabindex="0"
              class="sapUiPseudoInvisibleText sapMSltHiddenSelect"
            >
              Label Type Brackets
            </div>
            <input
              id="__select0-hiddenInput"
              name=""
              value="labelTypeBrackets"
              aria-readonly="true"
              tabindex="-1"
              aria-hidden="true"
              type="hidden"
              class="sapUiPseudoInvisibleText"
            /><span id="__select0-label" aria-hidden="true" class="sapMSltLabel"
              ><span
                id="sap-ui-invisible-__select0-labelIcon"
                data-sap-ui="sap-ui-invisible-__select0-labelIcon"
                aria-hidden="true"
                class="sapUiHiddenPlaceholder"
              ></span
              ><span id="__select0-labelText" class="sapMSelectListItemText"
                >Label Type Brackets</span
              ></span
            ><span
              id="__select0-arrow"
              aria-hidden="true"
              class="sapMSltArrow"
            ></span>
            <ul
              tabindex="-1"
              role="listbox"
              class="sapMSelectList"
              style="width: 100%"
            >
              <li
                tabindex="0"
                role="option"
                aria-selected="true"
                aria-setsize="2"
                aria-posinset="1"
                class="sapMSelectListItemBase sapMSelectListItem sapMSelectListItemBaseHoverable sapMSelectListItemBaseSelected"
              >
                Label Type Brackets
              </li>
              <li
                tabindex="0"
                role="option"
                aria-selected="false"
                aria-setsize="2"
                aria-posinset="2"
                class="sapMSelectListItemBase sapMSelectListItem sapMSelectListItemBaseHoverable"
              >
                Label
              </li>
            </ul>
          </div>
        </div>
        <div
          id="__form0--FC-NoHead--Grid-wrapperfor-__label10"
          class="sapUiRespGridBreak sapUiRespGridSpanXL3 sapUiRespGridSpanL3 sapUiRespGridSpanM3 sapUiRespGridSpanS12 sapUiFormElementLbl"
        >
          <label
            id="__label10"
            data-sap-ui="__label10"
            for="__select1-hiddenSelect"
            class="sapMLabel sapUiSelectable sapMLabelWrapped sapMLabelMaxWidth sapUiFormLabel-CTX"
            style="text-align: left"
            ><span id="__label10-text" class="sapMLabelTextWrapper"
              ><bdi id="__label10-bdi">Decimal Separator</bdi></span
            ><span
              data-colon=":"
              aria-hidden="true"
              class="sapMLabelColonAndRequired"
            ></span
          ></label>
        </div>
        <div
          id="__form0--FC-NoHead--Grid-wrapperfor-__select1"
          class="sapUiRespGridSpanXL9 sapUiRespGridSpanL9 sapUiRespGridSpanM9 sapUiRespGridSpanS12"
        >
          <div
            id="__select1"
            data-sap-ui="__select1"
            tabindex="-1"
            class="sapMSlt sapMSltDefault sapMSltMinWidth sapMSltHoverable sapMSltWithArrow"
            style="width: 100%; max-width: 100%"
          >
            <div
              id="__select1-hiddenSelect"
              role="combobox"
              aria-roledescription="Listbox"
              aria-readonly="false"
              aria-expanded="false"
              aria-labelledby="__label10"
              aria-haspopup="listbox"
              tabindex="0"
              class="sapUiPseudoInvisibleText sapMSltHiddenSelect"
            >
              Browser Default
            </div>
            <input
              id="__select1-hiddenInput"
              name=""
              value=""
              aria-readonly="true"
              tabindex="-1"
              aria-hidden="true"
              type="hidden"
              class="sapUiPseudoInvisibleText"
            /><span id="__select1-label" aria-hidden="true" class="sapMSltLabel"
              ><span
                id="sap-ui-invisible-__select1-labelIcon"
                data-sap-ui="sap-ui-invisible-__select1-labelIcon"
                aria-hidden="true"
                class="sapUiHiddenPlaceholder"
              ></span
              ><span id="__select1-labelText" class="sapMSelectListItemText"
                >Browser Default</span
              ></span
            ><span
              id="__select1-arrow"
              aria-hidden="true"
              class="sapMSltArrow"
            ></span>
            <ul
              tabindex="-1"
              role="listbox"
              class="sapMSelectList"
              style="width: 100%"
            >
              <li
                tabindex="0"
                role="option"
                aria-selected="true"
                aria-setsize="3"
                aria-posinset="1"
                class="sapMSelectListItemBase sapMSelectListItem sapMSelectListItemBaseHoverable sapMSelectListItemBaseSelected"
              >
                Browser Default
              </li>
              <li
                tabindex="0"
                role="option"
                aria-selected="false"
                aria-setsize="3"
                aria-posinset="2"
                class="sapMSelectListItemBase sapMSelectListItem sapMSelectListItemBaseHoverable"
              >
                Comma `,`
              </li>
              <li
                tabindex="0"
                role="option"
                aria-selected="false"
                aria-setsize="3"
                aria-posinset="3"
                class="sapMSelectListItemBase sapMSelectListItem sapMSelectListItemBaseHoverable"
              >
                Dot `.`
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

  ```

</details>

**Comment by marianfoo** [comment]
Thanks @Siolto it works!
But not for `1.71` with `ancestor`.
Do you have experience with that?

**Comment by marianfoo** [comment]
Almost works ;)
created a new issue for this, i see this as a other issue 
#491
