### ISSUE TITLE
What credentials are needed to run the authentication:basic-auth test?

### ISSUE THREAD

**Issue by gregorwolf** [ui5-community/wdi5#517]
**Describe the bug**
To help with #502 I try to start with the included test "authentication:basic-auth". But when I run this test without any further configuration I get this output:

```
> ui5-ts-app@0.8.15-notimportant authentication:basic-auth
> wdio run test/e2e/authentication/wdio-basic-auth-authentication.conf.ts


Execution of 2 workers started at 2023-08-23T11:25:13.286Z

[0-1] RUNNING in chrome - /test/e2e/Authentication.test.ts
[0-0] RUNNING in chrome - /test/e2e/Basic.test.ts
[0-1] 2023-08-23T11:25:40.142Z ERROR webdriver: Request failed with status 400 due to invalid cookie domain: invalid cookie domain
[0-1]   (Session info: chrome=116.0.5845.110)
[0-1] /Users/gwolf/Documents/Projects/ui5/wdi5/node_modules/webdriver/build/utils.js:198
[0-1]     return new CustomRequestError(body, requestOptions);
[0-1]            ^
[0-1] invalid cookie domain: invalid cookie domain
[0-1]   (Session info: chrome=116.0.5845.110)
[0-1]     at getErrorFromResponseBody (/Users/gwolf/Documents/Projects/ui5/wdi5/node_modules/webdriver/build/utils.js:198:12)
[0-1]     at NodeJSRequest._request (/Users/gwolf/Documents/Projects/ui5/wdi5/node_modules/webdriver/build/request/index.js:166:60)
[0-1]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[0-1]     at async Browser.wrapCommandFn (/Users/gwolf/Documents/Projects/ui5/wdi5/node_modules/@wdio/utils/build/shim.js:137:29)
[0-1]     at async Browser.setCookies (/Users/gwolf/Documents/Projects/ui5/wdi5/node_modules/webdriverio/build/commands/browser/setCookies.js:63:9)
[0-1]     at async Browser.wrapCommandFn (/Users/gwolf/Documents/Projects/ui5/wdi5/node_modules/@wdio/utils/build/shim.js:137:29)
[0-1] FAILED in chrome - /test/e2e/Authentication.test.ts
[0-0] 2023-08-23T11:25:40.189Z ERROR webdriver: Request failed with status 400 due to invalid cookie domain: invalid cookie domain
[0-0]   (Session info: chrome=116.0.5845.110)
[0-0] /Users/gwolf/Documents/Projects/ui5/wdi5/node_modules/webdriver/build/utils.js:198
[0-0]     return new CustomRequestError(body, requestOptions);
[0-0]            ^
[0-0] invalid cookie domain: invalid cookie domain
[0-0]   (Session info: chrome=116.0.5845.110)
[0-0]     at getErrorFromResponseBody (/Users/gwolf/Documents/Projects/ui5/wdi5/node_modules/webdriver/build/utils.js:198:12)
[0-0]     at NodeJSRequest._request (/Users/gwolf/Documents/Projects/ui5/wdi5/node_modules/webdriver/build/request/index.js:166:60)
[0-0]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[0-0]     at async Browser.wrapCommandFn (/Users/gwolf/Documents/Projects/ui5/wdi5/node_modules/@wdio/utils/build/shim.js:137:29)
[0-0]     at async Browser.setCookies (/Users/gwolf/Documents/Projects/ui5/wdi5/node_modules/webdriverio/build/commands/browser/setCookies.js:63:9)
[0-0]     at async Browser.wrapCommandFn (/Users/gwolf/Documents/Projects/ui5/wdi5/node_modules/@wdio/utils/build/shim.js:137:29)
[0-0] FAILED in chrome - /test/e2e/Basic.test.ts

Spec Files:      0 passed, 2 failed, 2 total (100% completed) in 00:00:26 

npm ERR! Lifecycle script `authentication:basic-auth` failed with error: 
npm ERR! Error: command failed 
npm ERR!   in workspace: ui5-ts-app@0.8.15-notimportant 
npm ERR!   at location: /Users/gwolf/Documents/Projects/ui5/wdi5/examples/ui5-ts-app 
```

**To Reproduce**

1. Clone this repository
2. Install the npm packages
3. Run 'npm run authentication:basic-auth -w examples/ui5-ts-app'

**Expected behavior**
Provide instructions for a contributor what credentials can be used for basic authentication.

**Comment by vobu** [comment]
this already got into `wdi5` 2.0: https://ui5-community.github.io/wdi5/#/authentication?id=cap-authentication-only-during-development
