### ISSUE TITLE
 Error: Polling stopped because the timeout of 999999 milliseconds has been reached but there is still pending asynchronous work

### ISSUE THREAD

**Issue by LindsayWangGreat** [ui5-community/wdi5#594]
**Describe the bug**
A clear and concise description of what the bug :bug: is
I am working on wdi5 test case. But I met an issue that I can see the element is showing inside the browser, but the test doesn't proceed and shows time out after some milliseconds. I even thought it might caused by the small timeout so I extend it to 999999. It doesn't work still.
From the error in console of the F12. It says
`
 Error: Polling stopped because the timeout of 999999 milliseconds has been reached but there is still pending asynchronous work.
**To ReproThis is the last log of pending work:
There are 1 open XHRs and 0 open FakeXHRs.
XHR: URL: '/sap/opu/odata/sap/xxxx_SRV/xxxx_CV_InitiateAudit(guid'f9860dd1-e5e8-4266-bf05-4ab115a8e2f9')/to_UserRole?sap-client=990&$orderby=userSequence%20asc' Method: 'GET' Async: 'true'
Stack:     at Object.r [as resolveStackTrace] (https://ldcifrt.wdf.sap.corp:44300/sap/bc/ui5_ui5/ui2/ushell/resources/~20220928081100~/sap/ui/test/autowaiter/_utils.js?eval:6:117)
    at XMLHttpRequest.d (_XHRWaiter.js?eval:6:1332)
    at XMLHttpRequest.send (_XHRWaiter.js?eval:6:981)
    at Object.request (datajs-dbg.js:2592:20)
    at E2 (datajs-dbg.js:1615:26)
    at o.request (datajs-dbg.js:7957:20)
    at T._request (ODataModel-dbg.js:7290:25)
    at f1 (ODataModel-dbg.js:3434:25)
    at ODataModel-dbg.js:3395:5
    at :44300/sap/bc/ui2/v (https://ldcifrt.wdf.sap.corp:44300/sap/bc/ui5_ui5/ui2/ushell/resources/~20220928081100~/sap/ui/test/autowaiter/_promiseWaiter.js?eval:6:2327) -  sap.ui.test.autowaiter._XHRWaiter#hasPending
    at eval (eval at executeAsyncScript (flp:447:26), <anonymous>:74:47)
    at n (_autoWaiterAsync.js?eval:6:1187)
    at h (_autoWaiterAsync.js?eval:6:969)
    at eval (_autoWaiterAsync.js?eval:6:830)
    at u (_timeoutWaiter.js?eval:6:1517)duce**
`
Actually, I test it manually, in the F12 network I didn't see such pending request.
Do you know how to analyze further on this issue?

**Expected behavior**

**Logs/Console Output**
`
 Error: Polling stopped because the timeout of 999999 milliseconds has been reached but there is still pending asynchronous work.
**To ReproThis is the last log of pending work:
There are 1 open XHRs and 0 open FakeXHRs.
XHR: URL: '/sap/opu/odata/sap/xxxx_SRV/xxxx_CV_InitiateAudit(guid'f9860dd1-e5e8-4266-bf05-4ab115a8e2f9')/to_UserRole?sap-client=990&$orderby=userSequence%20asc' Method: 'GET' Async: 'true'
Stack:     at Object.r [as resolveStackTrace] (https://ldcifrt.wdf.sap.corp:44300/sap/bc/ui5_ui5/ui2/ushell/resources/~20220928081100~/sap/ui/test/autowaiter/_utils.js?eval:6:117)
    at XMLHttpRequest.d (_XHRWaiter.js?eval:6:1332)
    at XMLHttpRequest.send (_XHRWaiter.js?eval:6:981)
    at Object.request (datajs-dbg.js:2592:20)
    at E2 (datajs-dbg.js:1615:26)
    at o.request (datajs-dbg.js:7957:20)
    at T._request (ODataModel-dbg.js:7290:25)
    at f1 (ODataModel-dbg.js:3434:25)
    at ODataModel-dbg.js:3395:5
    at :44300/sap/bc/ui2/v (https://ldcifrt.wdf.sap.corp:44300/sap/bc/ui5_ui5/ui2/ushell/resources/~20220928081100~/sap/ui/test/autowaiter/_promiseWaiter.js?eval:6:2327) -  sap.ui.test.autowaiter._XHRWaiter#hasPending
    at eval (eval at executeAsyncScript (flp:447:26), <anonymous>:74:47)
    at n (_autoWaiterAsync.js?eval:6:1187)
    at h (_autoWaiterAsync.js?eval:6:969)
    at eval (_autoWaiterAsync.js?eval:6:830)
    at u (_timeoutWaiter.js?eval:6:1517)duce**
`

**Screenshots**
if applicable, add screenshots to help explain your problem.

**Runtime Env (please complete the following information):**

- `wdi5/wdio-ui5-service`-version: "^2.0.4"
- `UI5` version:1.102.8 && 1.114.0
- `wdio`-version (output of `wdio --version`): "^8.32.2",
- `node`-version (output of `node --version`): v21.6.1
- OS: ios
- Browser + Version  122.0.6261.94

**Additional context**
Add any other context about the problem here,
e.g. any options the target browser is started with like `--headless` or
if the tests run in a CI environment

**Comment by vobu** [comment]
this sounds as if the OData request to `/sap/opu/odata/sap/xxxx_SRV/xxxx_CV_InitiateAudit` is either verrrry slow or not working in the CI environment → start exploring from there.
If you're actually continuously polling that endpoint in your app, the pending network request hinders any progress of the UI5 lifecycle. This can be mitigated by excluding the request from UI5's `autoWaiter` as described in https://ui5-community.github.io/wdi5/#/configuration?id=ignoreautowaiturls, example at https://github.com/ui5-community/wdi5/blob/fda2317c6675178deb0d57bdf8151b4d833846fb/examples/ui5-js-app/e2e-test-config/wdio-ui5tooling.conf.js#L9

**Comment by LindsayWangGreat** [comment]
great! works for me! Thank you!
