### ISSUE TITLE
3.0.0-rc.0: TypeError: browserInstance.goTo is not a function

### ISSUE THREAD

**Issue by xLexip** [ui5-community/wdi5#648]
**To Reproduce**
I have a basic test with 

```
before(async function () {
	await wdi5.goTo({ sHash: "#/business-objects" });
});
```

**Logs/Console Output**
```
[...]

[firefox 134.0a1 linux #0-0] browserInstance.goTo is not a function
[firefox 134.0a1 linux #0-0] TypeError: browserInstance.goTo is not a function
[firefox 134.0a1 linux #0-0]     at Function.<anonymous> (/builds/project/node_modules/wdio-ui5-service/src/wdi5.ts:117:35)
[firefox 134.0a1 linux #0-0]     at step (/builds/project/node_modules/wdio-ui5-service/cjs/wdi5.js:33:23)
[firefox 134.0a1 linux #0-0]     at Object.next (/builds/project/node_modules/wdio-ui5-service/cjs/wdi5.js:14:53)
[firefox 134.0a1 linux #0-0]     at /builds/project/node_modules/wdio-ui5-service/cjs/wdi5.js:8:71
[firefox 134.0a1 linux #0-0]     at new Promise (<anonymous>)
[firefox 134.0a1 linux #0-0]     at __awaiter (/builds/project/node_modules/wdio-ui5-service/cjs/wdi5.js:4:12)
[firefox 134.0a1 linux #0-0]     at Function.wdi5.goTo (/builds/project/node_modules/wdio-ui5-service/src/wdi5.ts:105:5)
[firefox 134.0a1 linux #0-0]     at Context.<anonymous> (/builds/project/test/app/e2e-tests/business-objects/bo-templates.test.js:16:14)
Spec Files:	 0 passed, 3 failed, 3 total (100% completed) in 00:00:48  
```

**Runtime Env (please complete the following information):**

- `wdi5/wdio-ui5-service`: **3.0.0-rc.0**
- `UI5`: 1.120 LTS/LATEST
- `wdio`: **9.2.1**
- `node`: 20.15.1
- `OS`: Ubuntu LTS
- `Browser`: firefox (v134.0a1)

**Additional context**
The test are run in an GitLab CI environment with `--headless`.

**Comment by Siolto** [comment]
Hi @xLexip,

thanks for reporting this issue. I could reproduce it. 

It seems like since v9 the hooks have changed their internal behavior. We need to investigate this further. As a workaround you could move your `wdi5.goTo(...)` directly into an `it(...)` step.

Regards
Simon

**Comment by xLexip** [comment]
Thanks for the reply @Siolto. 
This does not seem be a problem with just WDIO v9, as it also happens for us after updating to CDS **v8** with WDIO **v8** and WDI5 **v2**:

```
"@sap/cds": "8.4.1",
"@sap/cds-dk": "8.4.1",
"@wdio/cli": "8.40.6",
"@wdio/junit-reporter": "8.40.6",
"@wdio/local-runner": "8.40.6",
"@wdio/mocha-framework": "8.40.6",
"@wdio/spec-reporter": "8.40.6",
"wdio-ui5-service": "2.0.10",
```

```
{"message"=>"browserInstance.goTo is not a function"}

System Err:

TypeError: browserInstance.goTo is not a function
    at Function.<anonymous> (/builds/sap/service/node_modules/wdio-ui5-service/cjs/wdi5.js:161:62)
    at step (/builds/sap/service/node_modules/wdio-ui5-service/cjs/wdi5.js:33:23)
    at Object.next (/builds/sap/service/node_modules/wdio-ui5-service/cjs/wdi5.js:14:53)
    at /builds/sap/service/node_modules/wdio-ui5-service/cjs/wdi5.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/builds/sap/service/node_modules/wdio-ui5-service/cjs/wdi5.js:4:12)
    at wdi5.goTo (/builds/sap/service/node_modules/wdio-ui5-service/cjs/wdi5.js:136:16)
    at Context.<anonymous> (/builds/sap/service/test/app/e2e-tests/dashboard/dashboard.test.js:8:14)
```

Moving `browserInstance.goTo` into an it() does not help...

**Comment by xLexip** [comment]
Hello again?

**Comment by heimwege** [comment]
@Siolto or @vobu can we please re-open this one? I've fallen into the same trap 🙈
The wdi5 types also still proposes `goTo` e.g. in the `before` hook which crashes at runtime.
The proposed workaround directly using it in the `it` works 👍🏻

**Comment by vobu** [comment]
we're still having major performance issues w/ `wdi5^3` ↔︎ `wdio^9` - so even though this is meh, there's currently some bigger fish to catch first 😬

**Comment by heimwege** [comment]
Bump to keep it open

**Comment by heimwege** [comment]
Bump

**Comment by Siolto** [comment]
Hey @xLexip @heimwege: Is this issue still a problem for you? I just tried to reproduce it again and for me `wdi5.goTo` is now working in the before hook 🧙

**Comment by heimwege** [comment]
Hm. I also don't see it any longer (w/o updating any dependency version, which confuses me a bit 🤷🏻)

**Comment by xLexip** [comment]
doesn't happen for me neither anymore. So I'll close this. :]
